### ISSUE TITLE
Relay type does not conform to inherited Observable type

### ISSUE THREAD

**Issue by luisnaranjo733** [Microsoft/RxRelayJS#3]
A relay should be assignable to an observable type. A common use case of a relay is to return it as an observable so downstream consumers can just treat it as an ordinary observable.

[ts]
Type 'Relay<Token>' is not assignable to type 'Observable<Token>'.
  Property '_subscribe' is protected in type 'Relay<Token>' but public in type 'Observable<Token>'.

**Comment by luisnaranjo733** [comment]
@Fitzpasd Is this intentional?

**Comment by Fitzpasd** [comment]
You were likely using an unsupported (newer) version of RxJS.  Updated to 5.5.11 for now which should fix this issue.  Will look to upgrade to 6 in the near future.
