### ISSUE TITLE
Any plans to move to RxJS 6.x.x?

### ISSUE THREAD

**Issue by NeverwinterMoon** [Microsoft/RxRelayJS#4]
Is there any chance the dependency version will be updated? Right now `rxjs-compat` is required for the interop.

**Comment by Fitzpasd** [comment]
Been on my backlog for a while.  I'll bump it up now and hopefully get this in soon.

**Comment by Fitzpasd** [comment]
Just published v1.0.3 which uses RxJS 6.  Thanks to @devholic  for the contribution.
